[build]
  command = "npm run build:netlify"
  publish = "dist/nesa-web-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16.20"
  NPM_VERSION = "8"
  NPM_FLAGS = "--legacy-peer-deps"
